[package]
name = "itos"
version = "0.1.0"
authors = ["Takeshi Tsukamoto <itometeam@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["staticlib"]

[dependencies]
